image: node:18.9.0

pipelines:
  branches:
    main:
      - step:
          name: Build & Push to ECR
          services:
            - docker
          script:
            - yarn version --patch
            - export VERSION=$(node -e "console.log(require('./package.json').version)")
            - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awc-cli.zip"
            - unzip awc-cli.zip
            - ./aws/install
            -  aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin "$AWS_ECR_REPO_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com"
            - IMAGE="$AWS_ECR_REPO_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$AWS_ECR_REPO_NAME:$VERSION"
            - docker build -t $AWS_ECR_REPO_NAME:$VERSION .
            - docker tag $AWS_ECR_REPO_NAME:$VERSION $IMAGE
            - docker push $IMAGE
      - step:
          name: Release to Rancher
          deployment: production
          script:
            - ./release.sh
