image: node:18.9.0

# TODO: implement version creation rollback in case of failure
# see https://bitbucket.org/blog/after-scripts-now-available-for-bitbucket-pipelines

pipelines:
  branches:
    main:
      - step:
          name: Create version
          script:
            - yarn config set version-git-message "[skip ci] - version %s - build no $BITBUCKET_BUILD_NUMBER"
            - yarn version --patch
            - git push --follow-tags

      - step:
          name: Build & Push to ECR
          services:
            - docker
          script:
            - VERSION=$(node -e "console.log(require('./package.json').version)")
            - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awc-cli.zip"
            - unzip awc-cli.zip
            - ./aws/install
            - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin "$AWS_ECR_REPO_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com"
            - IMAGE="$AWS_ECR_REPO_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$AWS_ECR_REPO_NAME:$VERSION"
            - docker build -t $AWS_ECR_REPO_NAME:$VERSION .
            - docker tag $AWS_ECR_REPO_NAME:$VERSION $IMAGE
            - docker push $IMAGE
